// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/service/actions.go
//
// Generated by this command:
//
//	mockgen -source=pkg/service/actions.go -destination=pkg/service/mocks/actions_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	serviceextension "extend-eac-policy/pkg/pb"
	service "extend-eac-policy/pkg/service"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockActionHandler is a mock of ActionHandler interface.
type MockActionHandler struct {
	ctrl     *gomock.Controller
	recorder *MockActionHandlerMockRecorder
	isgomock struct{}
}

// MockActionHandlerMockRecorder is the mock recorder for MockActionHandler.
type MockActionHandlerMockRecorder struct {
	mock *MockActionHandler
}

// NewMockActionHandler creates a new mock instance.
func NewMockActionHandler(ctrl *gomock.Controller) *MockActionHandler {
	mock := &MockActionHandler{ctrl: ctrl}
	mock.recorder = &MockActionHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockActionHandler) EXPECT() *MockActionHandlerMockRecorder {
	return m.recorder
}

// ApplyBan mocks base method.
func (m *MockActionHandler) ApplyBan(ctx context.Context, req *serviceextension.EACReportRequest, plan service.Reaction) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ApplyBan", ctx, req, plan)
	ret0, _ := ret[0].(error)
	return ret0
}

// ApplyBan indicates an expected call of ApplyBan.
func (mr *MockActionHandlerMockRecorder) ApplyBan(ctx, req, plan any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ApplyBan", reflect.TypeOf((*MockActionHandler)(nil).ApplyBan), ctx, req, plan)
}

// SendTelemetry mocks base method.
func (m *MockActionHandler) SendTelemetry(ctx context.Context, req *serviceextension.EACReportRequest, plan service.Reaction, source string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendTelemetry", ctx, req, plan, source)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendTelemetry indicates an expected call of SendTelemetry.
func (mr *MockActionHandlerMockRecorder) SendTelemetry(ctx, req, plan, source any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendTelemetry", reflect.TypeOf((*MockActionHandler)(nil).SendTelemetry), ctx, req, plan, source)
}

// SubmitReport mocks base method.
func (m *MockActionHandler) SubmitReport(ctx context.Context, req *serviceextension.EACReportRequest, source string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SubmitReport", ctx, req, source)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SubmitReport indicates an expected call of SubmitReport.
func (mr *MockActionHandlerMockRecorder) SubmitReport(ctx, req, source any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SubmitReport", reflect.TypeOf((*MockActionHandler)(nil).SubmitReport), ctx, req, source)
}
