// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.9
// source: service.proto

package serviceextension

import (
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ClientActionReason int32

const (
	ClientActionReason_ACTION_INVALID_UNSPECIFIED   ClientActionReason = 0
	ClientActionReason_ACTION_INTERNAL_ERROR        ClientActionReason = 1
	ClientActionReason_ACTION_INVALID_MESSAGE       ClientActionReason = 2
	ClientActionReason_ACTION_AUTHENTICATION_FAILED ClientActionReason = 3
	ClientActionReason_ACTION_NULL_CLIENT           ClientActionReason = 4
	ClientActionReason_ACTION_HEARTBEAT_TIMEOUT     ClientActionReason = 5
	ClientActionReason_ACTION_CLIENT_VIOLATION      ClientActionReason = 6
	ClientActionReason_ACTION_BACKEND_VIOLATION     ClientActionReason = 7
	ClientActionReason_ACTION_TEMPORARY_COOLDOWN    ClientActionReason = 8
	ClientActionReason_ACTION_TEMPORARY_BANNED      ClientActionReason = 9
	ClientActionReason_ACTION_PERMANENT_BANNED      ClientActionReason = 10
)

// Enum value maps for ClientActionReason.
var (
	ClientActionReason_name = map[int32]string{
		0:  "ACTION_INVALID_UNSPECIFIED",
		1:  "ACTION_INTERNAL_ERROR",
		2:  "ACTION_INVALID_MESSAGE",
		3:  "ACTION_AUTHENTICATION_FAILED",
		4:  "ACTION_NULL_CLIENT",
		5:  "ACTION_HEARTBEAT_TIMEOUT",
		6:  "ACTION_CLIENT_VIOLATION",
		7:  "ACTION_BACKEND_VIOLATION",
		8:  "ACTION_TEMPORARY_COOLDOWN",
		9:  "ACTION_TEMPORARY_BANNED",
		10: "ACTION_PERMANENT_BANNED",
	}
	ClientActionReason_value = map[string]int32{
		"ACTION_INVALID_UNSPECIFIED":   0,
		"ACTION_INTERNAL_ERROR":        1,
		"ACTION_INVALID_MESSAGE":       2,
		"ACTION_AUTHENTICATION_FAILED": 3,
		"ACTION_NULL_CLIENT":           4,
		"ACTION_HEARTBEAT_TIMEOUT":     5,
		"ACTION_CLIENT_VIOLATION":      6,
		"ACTION_BACKEND_VIOLATION":     7,
		"ACTION_TEMPORARY_COOLDOWN":    8,
		"ACTION_TEMPORARY_BANNED":      9,
		"ACTION_PERMANENT_BANNED":      10,
	}
)

func (x ClientActionReason) Enum() *ClientActionReason {
	p := new(ClientActionReason)
	*p = x
	return p
}

func (x ClientActionReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ClientActionReason) Descriptor() protoreflect.EnumDescriptor {
	return file_service_proto_enumTypes[0].Descriptor()
}

func (ClientActionReason) Type() protoreflect.EnumType {
	return &file_service_proto_enumTypes[0]
}

func (x ClientActionReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ClientActionReason.Descriptor instead.
func (ClientActionReason) EnumDescriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{0}
}

type IntegrityViolationType int32

const (
	IntegrityViolationType_INTEGRITY_INVALID_UNSPECIFIED             IntegrityViolationType = 0
	IntegrityViolationType_INTEGRITY_CATALOG_NOT_FOUND               IntegrityViolationType = 1
	IntegrityViolationType_INTEGRITY_CATALOG_ERROR                   IntegrityViolationType = 2
	IntegrityViolationType_INTEGRITY_CATALOG_CERTIFICATE_REVOKED     IntegrityViolationType = 3
	IntegrityViolationType_INTEGRITY_CATALOG_MISSING_MAIN_EXECUTABLE IntegrityViolationType = 4
	IntegrityViolationType_INTEGRITY_GAME_FILE_MISMATCH              IntegrityViolationType = 5
	IntegrityViolationType_INTEGRITY_REQUIRED_GAME_FILE_NOT_FOUND    IntegrityViolationType = 6
	IntegrityViolationType_INTEGRITY_UNKNOWN_GAME_FILE_FORBIDDEN     IntegrityViolationType = 7
	IntegrityViolationType_INTEGRITY_SYSTEM_FILE_UNTRUSTED           IntegrityViolationType = 8
	IntegrityViolationType_INTEGRITY_FORBIDDEN_MODULE_LOADED         IntegrityViolationType = 9
	IntegrityViolationType_INTEGRITY_CORRUPTED_MEMORY                IntegrityViolationType = 10
	IntegrityViolationType_INTEGRITY_FORBIDDEN_TOOL_DETECTED         IntegrityViolationType = 11
	IntegrityViolationType_INTEGRITY_INTERNAL_ANTI_CHEAT_VIOLATION   IntegrityViolationType = 12
	IntegrityViolationType_INTEGRITY_CORRUPTED_NETWORK_MESSAGE_FLOW  IntegrityViolationType = 13
	IntegrityViolationType_INTEGRITY_VIRTUAL_MACHINE_NOT_ALLOWED     IntegrityViolationType = 14
	IntegrityViolationType_INTEGRITY_FORBIDDEN_SYSTEM_CONFIGURATION  IntegrityViolationType = 15
)

// Enum value maps for IntegrityViolationType.
var (
	IntegrityViolationType_name = map[int32]string{
		0:  "INTEGRITY_INVALID_UNSPECIFIED",
		1:  "INTEGRITY_CATALOG_NOT_FOUND",
		2:  "INTEGRITY_CATALOG_ERROR",
		3:  "INTEGRITY_CATALOG_CERTIFICATE_REVOKED",
		4:  "INTEGRITY_CATALOG_MISSING_MAIN_EXECUTABLE",
		5:  "INTEGRITY_GAME_FILE_MISMATCH",
		6:  "INTEGRITY_REQUIRED_GAME_FILE_NOT_FOUND",
		7:  "INTEGRITY_UNKNOWN_GAME_FILE_FORBIDDEN",
		8:  "INTEGRITY_SYSTEM_FILE_UNTRUSTED",
		9:  "INTEGRITY_FORBIDDEN_MODULE_LOADED",
		10: "INTEGRITY_CORRUPTED_MEMORY",
		11: "INTEGRITY_FORBIDDEN_TOOL_DETECTED",
		12: "INTEGRITY_INTERNAL_ANTI_CHEAT_VIOLATION",
		13: "INTEGRITY_CORRUPTED_NETWORK_MESSAGE_FLOW",
		14: "INTEGRITY_VIRTUAL_MACHINE_NOT_ALLOWED",
		15: "INTEGRITY_FORBIDDEN_SYSTEM_CONFIGURATION",
	}
	IntegrityViolationType_value = map[string]int32{
		"INTEGRITY_INVALID_UNSPECIFIED":             0,
		"INTEGRITY_CATALOG_NOT_FOUND":               1,
		"INTEGRITY_CATALOG_ERROR":                   2,
		"INTEGRITY_CATALOG_CERTIFICATE_REVOKED":     3,
		"INTEGRITY_CATALOG_MISSING_MAIN_EXECUTABLE": 4,
		"INTEGRITY_GAME_FILE_MISMATCH":              5,
		"INTEGRITY_REQUIRED_GAME_FILE_NOT_FOUND":    6,
		"INTEGRITY_UNKNOWN_GAME_FILE_FORBIDDEN":     7,
		"INTEGRITY_SYSTEM_FILE_UNTRUSTED":           8,
		"INTEGRITY_FORBIDDEN_MODULE_LOADED":         9,
		"INTEGRITY_CORRUPTED_MEMORY":                10,
		"INTEGRITY_FORBIDDEN_TOOL_DETECTED":         11,
		"INTEGRITY_INTERNAL_ANTI_CHEAT_VIOLATION":   12,
		"INTEGRITY_CORRUPTED_NETWORK_MESSAGE_FLOW":  13,
		"INTEGRITY_VIRTUAL_MACHINE_NOT_ALLOWED":     14,
		"INTEGRITY_FORBIDDEN_SYSTEM_CONFIGURATION":  15,
	}
)

func (x IntegrityViolationType) Enum() *IntegrityViolationType {
	p := new(IntegrityViolationType)
	*p = x
	return p
}

func (x IntegrityViolationType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (IntegrityViolationType) Descriptor() protoreflect.EnumDescriptor {
	return file_service_proto_enumTypes[1].Descriptor()
}

func (IntegrityViolationType) Type() protoreflect.EnumType {
	return &file_service_proto_enumTypes[1]
}

func (x IntegrityViolationType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use IntegrityViolationType.Descriptor instead.
func (IntegrityViolationType) EnumDescriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{1}
}

type AppliedAction int32

const (
	AppliedAction_UNSPECIFIED AppliedAction = 0
	AppliedAction_LOGGED      AppliedAction = 1
	AppliedAction_REPORTED    AppliedAction = 2
	AppliedAction_TEMP_BANNED AppliedAction = 3
	AppliedAction_PERM_BANNED AppliedAction = 4
)

// Enum value maps for AppliedAction.
var (
	AppliedAction_name = map[int32]string{
		0: "UNSPECIFIED",
		1: "LOGGED",
		2: "REPORTED",
		3: "TEMP_BANNED",
		4: "PERM_BANNED",
	}
	AppliedAction_value = map[string]int32{
		"UNSPECIFIED": 0,
		"LOGGED":      1,
		"REPORTED":    2,
		"TEMP_BANNED": 3,
		"PERM_BANNED": 4,
	}
)

func (x AppliedAction) Enum() *AppliedAction {
	p := new(AppliedAction)
	*p = x
	return p
}

func (x AppliedAction) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AppliedAction) Descriptor() protoreflect.EnumDescriptor {
	return file_service_proto_enumTypes[2].Descriptor()
}

func (AppliedAction) Type() protoreflect.EnumType {
	return &file_service_proto_enumTypes[2]
}

func (x AppliedAction) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AppliedAction.Descriptor instead.
func (AppliedAction) EnumDescriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{2}
}

type EACReportRequest struct {
	state                           protoimpl.MessageState `protogen:"open.v1"`
	UserId                          string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ClientActionReason              ClientActionReason     `protobuf:"varint,2,opt,name=client_action_reason,json=clientActionReason,proto3,enum=service.ClientActionReason" json:"client_action_reason,omitempty"`
	ClientActionDetailsReasonString string                 `protobuf:"bytes,3,opt,name=client_action_details_reason_string,json=clientActionDetailsReasonString,proto3" json:"client_action_details_reason_string,omitempty"`
	SessionId                       string                 `protobuf:"bytes,4,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields                   protoimpl.UnknownFields
	sizeCache                       protoimpl.SizeCache
}

func (x *EACReportRequest) Reset() {
	*x = EACReportRequest{}
	mi := &file_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EACReportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EACReportRequest) ProtoMessage() {}

func (x *EACReportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EACReportRequest.ProtoReflect.Descriptor instead.
func (*EACReportRequest) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{0}
}

func (x *EACReportRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *EACReportRequest) GetClientActionReason() ClientActionReason {
	if x != nil {
		return x.ClientActionReason
	}
	return ClientActionReason_ACTION_INVALID_UNSPECIFIED
}

func (x *EACReportRequest) GetClientActionDetailsReasonString() string {
	if x != nil {
		return x.ClientActionDetailsReasonString
	}
	return ""
}

func (x *EACReportRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type EACIntegrityReportRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	UserId           string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ViolationType    IntegrityViolationType `protobuf:"varint,2,opt,name=violation_type,json=violationType,proto3,enum=service.IntegrityViolationType" json:"violation_type,omitempty"`
	ViolationMessage string                 `protobuf:"bytes,3,opt,name=violation_message,json=violationMessage,proto3" json:"violation_message,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *EACIntegrityReportRequest) Reset() {
	*x = EACIntegrityReportRequest{}
	mi := &file_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EACIntegrityReportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EACIntegrityReportRequest) ProtoMessage() {}

func (x *EACIntegrityReportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EACIntegrityReportRequest.ProtoReflect.Descriptor instead.
func (*EACIntegrityReportRequest) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{1}
}

func (x *EACIntegrityReportRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *EACIntegrityReportRequest) GetViolationType() IntegrityViolationType {
	if x != nil {
		return x.ViolationType
	}
	return IntegrityViolationType_INTEGRITY_INVALID_UNSPECIFIED
}

func (x *EACIntegrityReportRequest) GetViolationMessage() string {
	if x != nil {
		return x.ViolationMessage
	}
	return ""
}

type EACReportResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	AppliedAction      AppliedAction          `protobuf:"varint,1,opt,name=applied_action,json=appliedAction,proto3,enum=service.AppliedAction" json:"applied_action,omitempty"`
	TelemetryRecorded  bool                   `protobuf:"varint,2,opt,name=telemetry_recorded,json=telemetryRecorded,proto3" json:"telemetry_recorded,omitempty"`
	ModerationReported bool                   `protobuf:"varint,3,opt,name=moderation_reported,json=moderationReported,proto3" json:"moderation_reported,omitempty"`
	BanDurationSeconds int64                  `protobuf:"varint,4,opt,name=ban_duration_seconds,json=banDurationSeconds,proto3" json:"ban_duration_seconds,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *EACReportResponse) Reset() {
	*x = EACReportResponse{}
	mi := &file_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EACReportResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EACReportResponse) ProtoMessage() {}

func (x *EACReportResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EACReportResponse.ProtoReflect.Descriptor instead.
func (*EACReportResponse) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{2}
}

func (x *EACReportResponse) GetAppliedAction() AppliedAction {
	if x != nil {
		return x.AppliedAction
	}
	return AppliedAction_UNSPECIFIED
}

func (x *EACReportResponse) GetTelemetryRecorded() bool {
	if x != nil {
		return x.TelemetryRecorded
	}
	return false
}

func (x *EACReportResponse) GetModerationReported() bool {
	if x != nil {
		return x.ModerationReported
	}
	return false
}

func (x *EACReportResponse) GetBanDurationSeconds() int64 {
	if x != nil {
		return x.BanDurationSeconds
	}
	return 0
}

var File_service_proto protoreflect.FileDescriptor

const file_service_proto_rawDesc = "" +
	"\n" +
	"\rservice.proto\x12\aservice\x1a\x1cgoogle/api/annotations.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\"\xe7\x01\n" +
	"\x10EACReportRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12M\n" +
	"\x14client_action_reason\x18\x02 \x01(\x0e2\x1b.service.ClientActionReasonR\x12clientActionReason\x12L\n" +
	"#client_action_details_reason_string\x18\x03 \x01(\tR\x1fclientActionDetailsReasonString\x12\x1d\n" +
	"\n" +
	"session_id\x18\x04 \x01(\tR\tsessionId\"\xa9\x01\n" +
	"\x19EACIntegrityReportRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12F\n" +
	"\x0eviolation_type\x18\x02 \x01(\x0e2\x1f.service.IntegrityViolationTypeR\rviolationType\x12+\n" +
	"\x11violation_message\x18\x03 \x01(\tR\x10violationMessage\"\xe4\x01\n" +
	"\x11EACReportResponse\x12=\n" +
	"\x0eapplied_action\x18\x01 \x01(\x0e2\x16.service.AppliedActionR\rappliedAction\x12-\n" +
	"\x12telemetry_recorded\x18\x02 \x01(\bR\x11telemetryRecorded\x12/\n" +
	"\x13moderation_reported\x18\x03 \x01(\bR\x12moderationReported\x120\n" +
	"\x14ban_duration_seconds\x18\x04 \x01(\x03R\x12banDurationSeconds*\xd7\x02\n" +
	"\x12ClientActionReason\x12\x1e\n" +
	"\x1aACTION_INVALID_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15ACTION_INTERNAL_ERROR\x10\x01\x12\x1a\n" +
	"\x16ACTION_INVALID_MESSAGE\x10\x02\x12 \n" +
	"\x1cACTION_AUTHENTICATION_FAILED\x10\x03\x12\x16\n" +
	"\x12ACTION_NULL_CLIENT\x10\x04\x12\x1c\n" +
	"\x18ACTION_HEARTBEAT_TIMEOUT\x10\x05\x12\x1b\n" +
	"\x17ACTION_CLIENT_VIOLATION\x10\x06\x12\x1c\n" +
	"\x18ACTION_BACKEND_VIOLATION\x10\a\x12\x1d\n" +
	"\x19ACTION_TEMPORARY_COOLDOWN\x10\b\x12\x1b\n" +
	"\x17ACTION_TEMPORARY_BANNED\x10\t\x12\x1b\n" +
	"\x17ACTION_PERMANENT_BANNED\x10\n" +
	"*\x93\x05\n" +
	"\x16IntegrityViolationType\x12!\n" +
	"\x1dINTEGRITY_INVALID_UNSPECIFIED\x10\x00\x12\x1f\n" +
	"\x1bINTEGRITY_CATALOG_NOT_FOUND\x10\x01\x12\x1b\n" +
	"\x17INTEGRITY_CATALOG_ERROR\x10\x02\x12)\n" +
	"%INTEGRITY_CATALOG_CERTIFICATE_REVOKED\x10\x03\x12-\n" +
	")INTEGRITY_CATALOG_MISSING_MAIN_EXECUTABLE\x10\x04\x12 \n" +
	"\x1cINTEGRITY_GAME_FILE_MISMATCH\x10\x05\x12*\n" +
	"&INTEGRITY_REQUIRED_GAME_FILE_NOT_FOUND\x10\x06\x12)\n" +
	"%INTEGRITY_UNKNOWN_GAME_FILE_FORBIDDEN\x10\a\x12#\n" +
	"\x1fINTEGRITY_SYSTEM_FILE_UNTRUSTED\x10\b\x12%\n" +
	"!INTEGRITY_FORBIDDEN_MODULE_LOADED\x10\t\x12\x1e\n" +
	"\x1aINTEGRITY_CORRUPTED_MEMORY\x10\n" +
	"\x12%\n" +
	"!INTEGRITY_FORBIDDEN_TOOL_DETECTED\x10\v\x12+\n" +
	"'INTEGRITY_INTERNAL_ANTI_CHEAT_VIOLATION\x10\f\x12,\n" +
	"(INTEGRITY_CORRUPTED_NETWORK_MESSAGE_FLOW\x10\r\x12)\n" +
	"%INTEGRITY_VIRTUAL_MACHINE_NOT_ALLOWED\x10\x0e\x12,\n" +
	"(INTEGRITY_FORBIDDEN_SYSTEM_CONFIGURATION\x10\x0f*\\\n" +
	"\rAppliedAction\x12\x0f\n" +
	"\vUNSPECIFIED\x10\x00\x12\n" +
	"\n" +
	"\x06LOGGED\x10\x01\x12\f\n" +
	"\bREPORTED\x10\x02\x12\x0f\n" +
	"\vTEMP_BANNED\x10\x03\x12\x0f\n" +
	"\vPERM_BANNED\x10\x042\xa1\x06\n" +
	"\x10AntiCheatService\x12\x94\x02\n" +
	"\x1eReportClientIntegrityViolation\x12\".service.EACIntegrityReportRequest\x1a\x1a.service.EACReportResponse\"\xb1\x01\x92Ay\x12!Submit client integrity violation\x1aFReceives EAC integrity violation report from the game client (public).b\f\n" +
	"\n" +
	"\n" +
	"\x06Bearer\x12\x00\x82\xd3\xe4\x93\x02/:\x01*\"*/v1/public/anti-cheat/eac/integrity/report\x12\xfb\x01\n" +
	"\x15ReportPublicViolation\x12\x19.service.EACReportRequest\x1a\x1a.service.EACReportResponse\"\xaa\x01\x92A|\x12\x1bSubmit client EAC violation\x1aOReceives EAC violation report from the game client and applies policy (public).b\f\n" +
	"\n" +
	"\n" +
	"\x06Bearer\x12\x00\x82\xd3\xe4\x93\x02%:\x01*\" /v1/public/anti-cheat/eac/report\x12\xf7\x01\n" +
	"\x14ReportAdminViolation\x12\x19.service.EACReportRequest\x1a\x1a.service.EACReportResponse\"\xa7\x01\x92Az\x12\x1bSubmit server EAC violation\x1aMReceives EAC violation report from dedicated server/admin and applies policy.b\f\n" +
	"\n" +
	"\n" +
	"\x06Bearer\x12\x00\x82\xd3\xe4\x93\x02$:\x01*\"\x1f/v1/admin/anti-cheat/eac/reportB\xbc\x01\x92AE\x12\x1f\n" +
	"\x18Anti-Cheat Reporting API2\x031.0\"\x01/Z\x1f\n" +
	"\x1d\n" +
	"\x06Bearer\x12\x13\b\x02\x1a\rAuthorization \x02\n" +
	"%net.accelbyte.extend.serviceextensionP\x01Z%accelbyte.net/extend/serviceextension\xaa\x02!AccelByte.Extend.ServiceExtensionb\x06proto3"

var (
	file_service_proto_rawDescOnce sync.Once
	file_service_proto_rawDescData []byte
)

func file_service_proto_rawDescGZIP() []byte {
	file_service_proto_rawDescOnce.Do(func() {
		file_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_service_proto_rawDesc), len(file_service_proto_rawDesc)))
	})
	return file_service_proto_rawDescData
}

var file_service_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_service_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_service_proto_goTypes = []any{
	(ClientActionReason)(0),           // 0: service.ClientActionReason
	(IntegrityViolationType)(0),       // 1: service.IntegrityViolationType
	(AppliedAction)(0),                // 2: service.AppliedAction
	(*EACReportRequest)(nil),          // 3: service.EACReportRequest
	(*EACIntegrityReportRequest)(nil), // 4: service.EACIntegrityReportRequest
	(*EACReportResponse)(nil),         // 5: service.EACReportResponse
}
var file_service_proto_depIdxs = []int32{
	0, // 0: service.EACReportRequest.client_action_reason:type_name -> service.ClientActionReason
	1, // 1: service.EACIntegrityReportRequest.violation_type:type_name -> service.IntegrityViolationType
	2, // 2: service.EACReportResponse.applied_action:type_name -> service.AppliedAction
	4, // 3: service.AntiCheatService.ReportClientIntegrityViolation:input_type -> service.EACIntegrityReportRequest
	3, // 4: service.AntiCheatService.ReportPublicViolation:input_type -> service.EACReportRequest
	3, // 5: service.AntiCheatService.ReportAdminViolation:input_type -> service.EACReportRequest
	5, // 6: service.AntiCheatService.ReportClientIntegrityViolation:output_type -> service.EACReportResponse
	5, // 7: service.AntiCheatService.ReportPublicViolation:output_type -> service.EACReportResponse
	5, // 8: service.AntiCheatService.ReportAdminViolation:output_type -> service.EACReportResponse
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_service_proto_init() }
func file_service_proto_init() {
	if File_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_service_proto_rawDesc), len(file_service_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_service_proto_goTypes,
		DependencyIndexes: file_service_proto_depIdxs,
		EnumInfos:         file_service_proto_enumTypes,
		MessageInfos:      file_service_proto_msgTypes,
	}.Build()
	File_service_proto = out.File
	file_service_proto_goTypes = nil
	file_service_proto_depIdxs = nil
}
