// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v3.21.9
// source: service.proto

package serviceextension

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AntiCheatService_ReportClientIntegrityViolation_FullMethodName = "/service.AntiCheatService/ReportClientIntegrityViolation"
	AntiCheatService_ReportPublicViolation_FullMethodName          = "/service.AntiCheatService/ReportPublicViolation"
	AntiCheatService_ReportAdminViolation_FullMethodName           = "/service.AntiCheatService/ReportAdminViolation"
)

// AntiCheatServiceClient is the client API for AntiCheatService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AntiCheatServiceClient interface {
	ReportClientIntegrityViolation(ctx context.Context, in *EACIntegrityReportRequest, opts ...grpc.CallOption) (*EACReportResponse, error)
	ReportPublicViolation(ctx context.Context, in *EACReportRequest, opts ...grpc.CallOption) (*EACReportResponse, error)
	ReportAdminViolation(ctx context.Context, in *EACReportRequest, opts ...grpc.CallOption) (*EACReportResponse, error)
}

type antiCheatServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAntiCheatServiceClient(cc grpc.ClientConnInterface) AntiCheatServiceClient {
	return &antiCheatServiceClient{cc}
}

func (c *antiCheatServiceClient) ReportClientIntegrityViolation(ctx context.Context, in *EACIntegrityReportRequest, opts ...grpc.CallOption) (*EACReportResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EACReportResponse)
	err := c.cc.Invoke(ctx, AntiCheatService_ReportClientIntegrityViolation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *antiCheatServiceClient) ReportPublicViolation(ctx context.Context, in *EACReportRequest, opts ...grpc.CallOption) (*EACReportResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EACReportResponse)
	err := c.cc.Invoke(ctx, AntiCheatService_ReportPublicViolation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *antiCheatServiceClient) ReportAdminViolation(ctx context.Context, in *EACReportRequest, opts ...grpc.CallOption) (*EACReportResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EACReportResponse)
	err := c.cc.Invoke(ctx, AntiCheatService_ReportAdminViolation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AntiCheatServiceServer is the server API for AntiCheatService service.
// All implementations should embed UnimplementedAntiCheatServiceServer
// for forward compatibility.
type AntiCheatServiceServer interface {
	ReportClientIntegrityViolation(context.Context, *EACIntegrityReportRequest) (*EACReportResponse, error)
	ReportPublicViolation(context.Context, *EACReportRequest) (*EACReportResponse, error)
	ReportAdminViolation(context.Context, *EACReportRequest) (*EACReportResponse, error)
}

// UnimplementedAntiCheatServiceServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAntiCheatServiceServer struct{}

func (UnimplementedAntiCheatServiceServer) ReportClientIntegrityViolation(context.Context, *EACIntegrityReportRequest) (*EACReportResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReportClientIntegrityViolation not implemented")
}
func (UnimplementedAntiCheatServiceServer) ReportPublicViolation(context.Context, *EACReportRequest) (*EACReportResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReportPublicViolation not implemented")
}
func (UnimplementedAntiCheatServiceServer) ReportAdminViolation(context.Context, *EACReportRequest) (*EACReportResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReportAdminViolation not implemented")
}
func (UnimplementedAntiCheatServiceServer) testEmbeddedByValue() {}

// UnsafeAntiCheatServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AntiCheatServiceServer will
// result in compilation errors.
type UnsafeAntiCheatServiceServer interface {
	mustEmbedUnimplementedAntiCheatServiceServer()
}

func RegisterAntiCheatServiceServer(s grpc.ServiceRegistrar, srv AntiCheatServiceServer) {
	// If the following call panics, it indicates UnimplementedAntiCheatServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AntiCheatService_ServiceDesc, srv)
}

func _AntiCheatService_ReportClientIntegrityViolation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EACIntegrityReportRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AntiCheatServiceServer).ReportClientIntegrityViolation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AntiCheatService_ReportClientIntegrityViolation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AntiCheatServiceServer).ReportClientIntegrityViolation(ctx, req.(*EACIntegrityReportRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AntiCheatService_ReportPublicViolation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EACReportRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AntiCheatServiceServer).ReportPublicViolation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AntiCheatService_ReportPublicViolation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AntiCheatServiceServer).ReportPublicViolation(ctx, req.(*EACReportRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AntiCheatService_ReportAdminViolation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EACReportRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AntiCheatServiceServer).ReportAdminViolation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AntiCheatService_ReportAdminViolation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AntiCheatServiceServer).ReportAdminViolation(ctx, req.(*EACReportRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AntiCheatService_ServiceDesc is the grpc.ServiceDesc for AntiCheatService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AntiCheatService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "service.AntiCheatService",
	HandlerType: (*AntiCheatServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ReportClientIntegrityViolation",
			Handler:    _AntiCheatService_ReportClientIntegrityViolation_Handler,
		},
		{
			MethodName: "ReportPublicViolation",
			Handler:    _AntiCheatService_ReportPublicViolation_Handler,
		},
		{
			MethodName: "ReportAdminViolation",
			Handler:    _AntiCheatService_ReportAdminViolation_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service.proto",
}
